### ISSUE TITLE
intial migration for staff app not working due to missing column in members

### ISSUE THREAD

**Issue by thilo** [nadineproject/nadine#110]
Hi! while trying to install nadine to have a look I came across a migration error: `django.db.utils.OperationalError: table staff_member__new has no column named tags`
I narrowed it down to https://github.com/nadineproject/nadine/blob/master/staff/migrations/0001_initial.py#L313 as it seems no tags column is added at https://github.com/nadineproject/nadine/blob/master/staff/migrations/0001_initial.py#L110 

I'm not really familiar with Python and Django I hope this helps anyway.

**Comment by jsayles** [comment]
I just went through and verified the initial steps and they work (on a
clean OS X Yosemite install).  I cleaned up the README to be more clear
while I was at it.  I'm thinking you are getting this error because you are
not in your virtualenv anymore.  Did you open a new window or close the
window and come back to it?  If so you will need to 'source bin/activate'
again to get back in the proper environment.

If that isn't it I suggest starting from scratch again and walking through
the steps.

**Comment by thilo** [comment]
Hi! Thanks for the fast response. I just followed the README again to set it up from scratch, only deviation before was that I kept the default sql_database config to spare me the trouble of dealing with postgres. Now that I'm using postgres it works. So I guess Postgres is not optional.

**Comment by jsayles** [comment]
Good to know! I hadn't fully tried it with SQLite.

**Comment by jsayles** [comment]
This came up again in #114 and I went in and made the default psql and removed the sqlite crap.
