### ISSUE TITLE
Verify django-ldapdb 1.0 works with LDAP Sync

### ISSUE THREAD

**Issue by jsayles** [nadineproject/nadine#388]
When ldap-sync was written django-ldapdb wasn't compatible with Django 2.0.  Version 1.0 has since been released and that should fix the issue. Please confirm compatibility.

**Comment by tnightingale** [comment]
Tested synchronizing and updating users to LDAP with latest django-ldapdb. Everything continues to work as expected. 

Only issue I encountered relates to the warning on the [pyldap dependency](https://github.com/pyldap/pyldap):

> Warning
> 
> Unfortunately, due to pip bug 4961, upgrading from previous versions using pip makes the ldap module unimportable.
> 
> Instead of upgrading, please replace pyldap by python-ldap in two separate steps:
> 
> ```
> python -m pip uninstall pyldap
> python -m pip install python-ldap
> ```
> If upgraded already issue, you can fix your environment by uninstalling and reinstalling python-ldap:
> 
> ```
> python -m pip uninstall python-ldap
> python -m pip install python-ldap
> ```
> We are sorry for the inconvenience. If you have a better solution, please join the discussion at pyldap bug 148.

On my existing code base I had to uninstall and reinstall python-ldap as mentioned due to an error when importing `ldap.filter`. **This isn't an issue on a fresh install.**
