### ISSUE TITLE
Billing Bug: Activity added to old, closed bill

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#409]
- User S.R. had activity (billable day) on Oct. 30. 
   - User properly logged in on the iPad console on 10/30/18.
- S.R.'s bill date is the 31st
- Activity was added to Bill 14721 (Due 3/12/18)
   - This activity would result in an overage charge
- Activity should have been added to Bill 15737 (Due 10/30/18)
   - This activity would not result in an overage charge
- Nadine is erroneously labeling Bill 14721 as "Overage Due" at /staff/billing/bills/outstanding/

**Comment by jsayles** [comment]
The issue here is that for some reason his first bill (14694) was not closed.  Having 2 bills open at one time would cause all sorts of weirdness.  It might have something to do with the fact that the start and end period of that bill are the same date.  

I manually closed 14694 and manually moved the Line Item for that coworking day to the appropriate bill.
