### ISSUE TITLE
"Introduction to Nadine" link does not work

### ISSUE THREAD

**Issue by mimorita** [nadineproject/nadine#430]
http://apps.officenomads.com/member/profile/

This link does not work, unless already logged in. This is the link sent with the into email.

**Comment by jsayles** [comment]
If you are not logged in, it redirects you to the login page.  If you then login on that page, it redirects you to your profile.  Is that not the behavior you are seeing or do you expect a different behavior?  Keep in mind the /member/profile link only knows it is you because you logged in.  This redirects you to your personal page /member/proflle/username.

**Comment by mimorita** [comment]
Gives an error message, "Not Found The requested URL was not found on this server." It does not redirect to the login page.

**Comment by jsayles** [comment]
For some reason the http->https redirect is not working but the URL should be https anyway.  I updated the link in the email.
